name: Auto Commit README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Runs every 1 hour
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update counter and README.md
        run: |
          COUNTER_FILE="counter.txt"
          README_FILE="README.md"

          # Initialize counter if not exist
          if [ ! -f "$COUNTER_FILE" ]; then
            echo "1" > "$COUNTER_FILE"
            count=1
          else
            count=$(cat "$COUNTER_FILE")
            count=$((count + 1))
            echo "$count" > "$COUNTER_FILE"
          fi

          # Update README.md
          timestamp=$(date -u)
          echo "- Commit #$count at $timestamp" >> "$README_FILE"

          # Save commit message to env for next step
          echo "NUMBER=$count" >> $GITHUB_ENV

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
        run: |
          git config --global user.name "rivopelu"
          git config --global user.email "rivopelu12@gmail.com"

          git add README.md counter.txt
          git commit -m "Auto commit #$NUMBER [skip ci]" || echo "No changes to commit"
          git pull --rebase || echo "No changes to rebase"
          git push --force https://x-access-token:${{ secrets.TOKEN_ACCESS }}@github.com/rivopelu/automation-commit.git main
