name: Auto Commit README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Runs every 1 hour
  workflow_dispatch:  # Allows manual execution

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents credential issues

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Update README.md with incrementing number
        run: |
          readme_path="README.md"

          # Initialize README.md if not exist
          if [ ! -f "$readme_path" ]; then
            echo "# Auto Commit README" > "$readme_path"
            echo "1" >> "$readme_path"
            echo "NUMBER=1" >> commit.env
          else
            # Extract last number (assumed to be the last line)
            last_number=$(tail -n 1 "$readme_path" | grep -o '[0-9]*')
            if [ -z "$last_number" ]; then
              new_number=1
            else
              new_number=$((last_number + 1))
            fi
            echo "$new_number" >> "$readme_path"
            echo "NUMBER=$new_number" >> commit.env
          fi

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACCESS }}
        run: |
          git config --global user.name "rivopelu"
          git config --global user.email "rivopelu12@gmail.com"

          # Load new number
          source commit.env
          COMMIT_MSG="Auto commit #$NUMBER"

          git add README.md
          git commit -m "$COMMIT_MSG [skip ci]" || echo "No changes to commit"

          git pull --rebase || echo "No changes to rebase"
          git push --force https://x-access-token:${{ secrets.TOKEN_ACCESS }}@github.com/rivopelu/automation-commit.git main
